<?php
declare(strict_types=1);
require_once __DIR__.'/../src/db.php';
require_once __DIR__.'/../src/auth.php';
require_once __DIR__.'/../src/ui.php';
require_teacher_or_admin();
$pdo=db();$id=trim($_GET['id']??'');
$stmt=$pdo->prepare("SELECT s.id,s.name,s.phone,s.email,s.status,s.created_at,COALESCE(sp.overall_level,'PRE-A1') overall_level,COALESCE(sp.estimated_level,'PRE-A1') estimated_level,COALESCE(sp.goal,'Aprender inglês') goal,COALESCE(sp.correction_mode,'balanced') correction_mode,COALESCE(sp.diagnostic_status,'pending') diagnostic_status,COALESCE(sp.diagnostic_step,0) diagnostic_step,sp.diagnostic_started_at,sp.diagnostic_completed_at,COALESCE(sp.grammar_score,0) grammar_score,COALESCE(sp.vocabulary_score,0) vocabulary_score,COALESCE(sp.speaking_score,0) speaking_score,COALESCE(sp.listening_score,0) listening_score,COALESCE(sp.reading_score,0) reading_score,COALESCE(sp.writing_score,0) writing_score,COALESCE(sp.fluency_score,0) fluency_score,COALESCE(sp.pronunciation_score,0) pronunciation_score,COALESCE(sp.xp,0) xp,COALESCE(sp.streak_days,0) streak_days,sp.last_study_at FROM students s LEFT JOIN student_profiles sp ON sp.student_id=s.id WHERE s.id=:id LIMIT 1");$stmt->execute(['id'=>$id]);$s=$stmt->fetch();if(!$s){http_response_code(404);exit('Aluno não encontrado.');}
$errorsStmt=$pdo->prepare("SELECT category,topic,original_text,corrected_text,explanation,severity,occurrences,mastery_score,next_review_at FROM student_errors WHERE student_id=:id AND status='learning' ORDER BY occurrences DESC,mastery_score ASC LIMIT 8");$errorsStmt->execute(['id'=>$id]);$errors=$errorsStmt->fetchAll();
$vocabStmt=$pdo->prepare("SELECT v.word,v.translation,v.example,v.level,sv.mastery_score,sv.next_review_at,sv.status FROM student_vocabulary sv JOIN vocabulary v ON v.id=sv.vocabulary_id WHERE sv.student_id=:id ORDER BY CASE WHEN sv.status IN ('learning','review') AND (sv.next_review_at IS NULL OR sv.next_review_at<=NOW()) THEN 0 ELSE 1 END,sv.next_review_at NULLS FIRST LIMIT 8");$vocabStmt->execute(['id'=>$id]);$vocab=$vocabStmt->fetchAll();
$vocabStatsStmt=$pdo->prepare("SELECT COUNT(*) FILTER(WHERE status='mastered') mastered,COUNT(*) FILTER(WHERE status IN ('learning','review')) learning,COUNT(*) FILTER(WHERE status IN ('learning','review') AND (next_review_at IS NULL OR next_review_at<=NOW())) due FROM student_vocabulary WHERE student_id=:id");$vocabStatsStmt->execute(['id'=>$id]);$vocabStats=$vocabStatsStmt->fetch();
$countsStmt=$pdo->prepare("SELECT (SELECT COUNT(*) FROM student_errors WHERE student_id=:id AND status='learning' AND (next_review_at IS NULL OR next_review_at<=NOW())) error_due,(SELECT COUNT(*) FROM student_activities WHERE student_id=:id AND status='pending') activities_due,(SELECT COUNT(*) FROM sessions WHERE student_id=:id) sessions_total,(SELECT COUNT(*) FROM weekly_reports WHERE student_id=:id) reports_total");$countsStmt->execute(['id'=>$id]);$counts=$countsStmt->fetch();
$sessionStmt=$pdo->prepare("SELECT id,created_at,ended_at,status,channel,mode,topic,COALESCE(conversation_topic,topic) conversation_topic,COALESCE(turn_count,0) turn_count,COALESCE(max_turns,10) max_turns,grammar_score,vocabulary_score,fluency_score FROM sessions WHERE student_id=:id ORDER BY created_at DESC LIMIT 10");$sessionStmt->execute(['id'=>$id]);$sessions=$sessionStmt->fetchAll();
$planStmt=$pdo->prepare("SELECT id,goal,target_level,start_date,end_date,plan_data,status FROM study_plans WHERE student_id=:id AND status='active' ORDER BY created_at DESC LIMIT 1");$planStmt->execute(['id'=>$id]);$plan=$planStmt->fetch()?:null;
$goalStmt=$pdo->prepare("SELECT * FROM weekly_goals WHERE student_id=:id ORDER BY week_start DESC LIMIT 1");$goalStmt->execute(['id'=>$id]);$goal=$goalStmt->fetch()?:null;
$diagnosticStmt=$pdo->prepare("SELECT estimated_level,strengths,weaknesses,detected_goals,written_feedback,study_plan,first_activity,created_at FROM diagnostic_reports WHERE student_id=:id ORDER BY created_at DESC LIMIT 1");$diagnosticStmt->execute(['id'=>$id]);$diagnostic=$diagnosticStmt->fetch()?:null;
$messageStmt=$pdo->prepare("SELECT role,content,transcription,message_type,created_at FROM messages WHERE student_id=:id ORDER BY created_at DESC LIMIT 6");$messageStmt->execute(['id'=>$id]);$messages=$messageStmt->fetchAll();
$skills=['Grammar'=>$s['grammar_score'],'Vocabulary'=>$s['vocabulary_score'],'Speaking'=>$s['speaking_score'],'Listening'=>$s['listening_score'],'Reading'=>$s['reading_score'],'Writing'=>$s['writing_score'],'Fluency'=>$s['fluency_score'],'Pronunciation'=>$s['pronunciation_score']];
$activitiesPct=$goal&&$goal['target_activities']>0?min(100,($goal['completed_activities']/$goal['target_activities'])*100):0;$minutesPct=$goal&&$goal['target_minutes']>0?min(100,($goal['completed_minutes']/$goal['target_minutes'])*100):0;$wordsPct=$goal&&$goal['target_words']>0?min(100,($goal['learned_words']/$goal['target_words'])*100):0;
$pageTitle=$s['name'];$pageSubtitle='Ficha pedagógica, desempenho, plano e histórico vinculados ao aluno.';require __DIR__.'/../templates/header.php';?>
<section class="student-head"><div style="display:flex;align-items:center;gap:17px"><div class="avatar avatar-lg"><?=e(ui_initials($s['name']))?></div><div><div class="list-meta"><span class="badge dark"><?=e($s['overall_level'])?></span><span class="badge dark"><?=e(ui_status_label($s['diagnostic_status']))?></span></div><h2><?=e($s['name'])?></h2><div class="label"><?=e($s['phone']?:$s['email']?:'Sem contato')?> · <?=e($s['goal'])?></div></div></div><div class="hero-stat"><strong><?= (int)$s['xp']?> XP</strong><span><?= (int)$s['streak_days']?> dias de sequência · <?=e(ui_relative_date($s['last_study_at']))?></span></div></section>
<section class="cards"><article class="card metric-card"><div><div class="label">Nível atual</div><div class="metric"><?=e($s['overall_level'])?></div><div class="metric-sub">Meta: <?=e($plan['target_level']??'A definir')?></div></div><div class="metric-icon"><?=ui_icon('progress')?></div></article><article class="card metric-card"><div><div class="label">Vocabulário em estudo</div><div class="metric"><?= (int)($vocabStats['learning']??0)?></div><div class="metric-sub"><?= (int)($vocabStats['mastered']??0)?> dominadas</div></div><div class="metric-icon"><?=ui_icon('vocabulary')?></div></article><article class="card metric-card"><div><div class="label">Pendências</div><div class="metric"><?= (int)($vocabStats['due']??0)+(int)$counts['error_due']+(int)$counts['activities_due']?></div><div class="metric-sub">Revisões e atividades</div></div><div class="metric-icon"><?=ui_icon('activities')?></div></article><article class="card metric-card"><div><div class="label">Sessões registradas</div><div class="metric"><?= (int)$counts['sessions_total']?></div><div class="metric-sub"><?= (int)$counts['reports_total']?> relatório(s) semanal(is)</div></div><div class="metric-icon"><?=ui_icon('reports')?></div></article></section>
<div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>Competências</h2><p>Pontuações consolidadas do perfil do aluno.</p></div></div><?php foreach($skills as $name=>$score):?><div class="skill"><div class="skill-head"><span><?=e($name)?></span><strong><?=number_format((float)$score,0)?>%</strong></div><div class="progress"><span data-progress="<?=ui_percent($score)?>"></span></div></div><?php endforeach;?></section><section class="panel"><div class="panel-head"><div><h2>Plano e meta semanal</h2><p>Objetivos vinculados ao planejamento ativo.</p></div></div><div class="list-card"><strong><?=e($plan['goal']??'Plano ainda não criado')?></strong><p><?= $plan?'Meta: '.e($plan['target_level']).' · '.e(ui_date_only($plan['start_date'])).' a '.e(ui_date_only($plan['end_date'])):'Conclua o diagnóstico para gerar o plano.'?></p></div><?php if($goal):?><div class="skill"><div class="skill-head"><span>Atividades</span><strong><?= (int)$goal['completed_activities']?>/<?= (int)$goal['target_activities']?></strong></div><div class="progress"><span data-progress="<?=$activitiesPct?>"></span></div></div><div class="skill"><div class="skill-head"><span>Minutos</span><strong><?= (int)$goal['completed_minutes']?>/<?= (int)$goal['target_minutes']?></strong></div><div class="progress"><span data-progress="<?=$minutesPct?>"></span></div></div><div class="skill"><div class="skill-head"><span>Palavras</span><strong><?= (int)$goal['learned_words']?>/<?= (int)$goal['target_words']?></strong></div><div class="progress"><span data-progress="<?=$wordsPct?>"></span></div></div><?php else:?><p class="muted">Nenhuma meta semanal registrada.</p><?php endif;?></section></div>
<div class="grid-2 section-gap"><section class="panel"><div class="panel-head"><div><h2>Erros recorrentes</h2><p>Prioridade definida por frequência e domínio.</p></div></div><?php if(!$errors):?><div class="empty-state"><h3>Nenhum erro recorrente</h3><p>As correções futuras aparecerão aqui.</p></div><?php else:foreach($errors as $error):?><div class="list-card"><div class="list-row"><strong><?=e($error['topic']?:$error['category']?:'Correção')?></strong><span class="badge warning"><?= (int)$error['occurrences']?>x</span></div><p><?=e($error['original_text']??'')?><?= $error['corrected_text']?' → '.e($error['corrected_text']):''?></p><?php if($error['explanation']):?><p><?=e($error['explanation'])?></p><?php endif;?><div class="progress slim" style="margin-top:10px"><span data-progress="<?=ui_percent($error['mastery_score'])?>"></span></div></div><?php endforeach;endif;?></section><section class="panel"><div class="panel-head"><div><h2>Vocabulário prioritário</h2><p>Palavras mais próximas da revisão.</p></div></div><?php if(!$vocab):?><div class="empty-state"><h3>Nenhuma palavra registrada</h3><p>O vocabulário aparecerá conforme as práticas.</p></div><?php else:foreach($vocab as $item):?><div class="list-card"><div class="list-row"><strong><?=e($item['word'])?></strong><span class="badge <?=e(ui_status_class($item['status']))?>"><?=e($item['translation']??ui_status_label($item['status']))?></span></div><p>Domínio <?=number_format((float)$item['mastery_score'],0)?>% · revisão <?=e(ui_date($item['next_review_at']))?></p></div><?php endforeach;endif;?></section></div>
<?php if($diagnostic):?><section class="panel section-gap"><div class="panel-head"><div><h2>Último diagnóstico</h2><p>Resultado salvo em <?=e(ui_date($diagnostic['created_at']))?>.</p></div><span class="badge <?=e(ui_level_class($diagnostic['estimated_level']))?>"><?=e($diagnostic['estimated_level'])?></span></div><div class="grid-3"><div><h3>Pontos fortes</h3><?php foreach(ui_json_array($diagnostic['strengths']) as $item):?><div class="list-card"><p style="margin:0"><?=e($item)?></p></div><?php endforeach;?></div><div><h3>Prioridades</h3><?php foreach(ui_json_array($diagnostic['weaknesses']) as $item):?><div class="list-card"><p style="margin:0"><?=e($item)?></p></div><?php endforeach;?></div><div><h3>Objetivos percebidos</h3><?php foreach(ui_json_array($diagnostic['detected_goals']) as $item):?><div class="list-card"><p style="margin:0"><?=e($item)?></p></div><?php endforeach;?><?php if($diagnostic['written_feedback']):?><div class="list-card"><p style="margin:0"><?=e($diagnostic['written_feedback'])?></p></div><?php endif;?></div></div></section><?php endif;?>
<section class="panel section-gap"><div class="panel-head"><div><h2>Sessões recentes</h2><p>Canal, modo, tema e desempenho de cada sessão.</p></div></div><?php if(!$sessions):?><div class="empty-state"><h3>Nenhuma sessão</h3><p>As conversas e avaliações aparecerão aqui.</p></div><?php else:?><div class="table-wrap"><table><thead><tr><th>Data</th><th>Canal</th><th>Modo</th><th>Tema</th><th>Status</th><th>Interações</th><th>Grammar</th><th>Fluency</th></tr></thead><tbody><?php foreach($sessions as $session):?><tr><td><?=e(ui_date($session['created_at']))?></td><td><?=e($session['channel']??'—')?></td><td><span class="badge neutral"><?=e(ui_status_label($session['mode']))?></span></td><td><?=e(ui_topic_label($session['conversation_topic']?:$session['topic']))?></td><td><span class="badge <?=e(ui_status_class($session['status']))?>"><?=e(ui_status_label($session['status']))?></span></td><td><?= (int)$session['turn_count']?>/<?= (int)$session['max_turns']?></td><td><?=$session['grammar_score']!==null?number_format((float)$session['grammar_score'],0).'%':'—'?></td><td><?=$session['fluency_score']!==null?number_format((float)$session['fluency_score'],0).'%':'—'?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if($messages):?><section class="panel section-gap"><div class="panel-head"><div><h2>Últimas mensagens</h2><p>Conteúdo vinculado ao histórico do aluno.</p></div></div><div class="timeline"><?php foreach($messages as $message):?><div class="timeline-item"><span class="timeline-dot"></span><strong><?= $message['role']==='teacher'?'Emma':'Aluno'?> · <?=e(ui_status_label($message['message_type']))?></strong><p><?=e(mb_strimwidth($message['content']?:$message['transcription']?:'',0,220,'…'))?></p><time><?=e(ui_date($message['created_at']))?></time></div><?php endforeach;?></div></section><?php endif;?>
<?php require __DIR__.'/../templates/footer.php';?>
