<?php

declare(strict_types=1);

require_once __DIR__ . '/../src/auth.php';
require_once __DIR__ . '/../src/ui.php';
require_once __DIR__ . '/../src/portal.php';
require_once __DIR__ . '/../src/progress.php';

require_teacher_or_admin();
$pdo = db();
$id = trim((string)($_GET['id'] ?? ''));
$m = progress_student_metrics($id, true);
if (!$m) { http_response_code(404); exit('Aluno não encontrado.'); }

$plan = portal_active_plan($id);
$diagnostic = portal_latest_diagnostic($id);
$history = progress_snapshot_history($id, 30);
$days = progress_student_daily_activity($id, 14);

$errorsStmt=$pdo->prepare("SELECT category,topic,original_text,corrected_text,explanation,severity,occurrences,mastery_score,next_review_at FROM student_errors WHERE student_id=:id AND status='learning' ORDER BY occurrences DESC,mastery_score ASC LIMIT 8");$errorsStmt->execute(['id'=>$id]);$errors=$errorsStmt->fetchAll();
$vocabStmt=$pdo->prepare("SELECT v.word,v.translation,v.example,v.level,sv.mastery_score,sv.next_review_at,sv.status FROM student_vocabulary sv JOIN vocabulary v ON v.id=sv.vocabulary_id WHERE sv.student_id=:id ORDER BY CASE WHEN sv.status IN ('learning','review') AND (sv.next_review_at IS NULL OR sv.next_review_at<=NOW()) THEN 0 ELSE 1 END,sv.next_review_at NULLS FIRST LIMIT 8");$vocabStmt->execute(['id'=>$id]);$vocab=$vocabStmt->fetchAll();
$sessionStmt=$pdo->prepare("SELECT id,created_at,ended_at,status,channel,mode,topic,COALESCE(conversation_topic,topic) conversation_topic,COALESCE(turn_count,0) turn_count,COALESCE(max_turns,10) max_turns,grammar_score,vocabulary_score,fluency_score FROM sessions WHERE student_id=:id ORDER BY created_at DESC LIMIT 10");$sessionStmt->execute(['id'=>$id]);$sessions=$sessionStmt->fetchAll();
$messageStmt=$pdo->prepare("SELECT role,content,transcription,message_type,created_at FROM messages WHERE student_id=:id ORDER BY created_at DESC LIMIT 6");$messageStmt->execute(['id'=>$id]);$messages=$messageStmt->fetchAll();

$skillLabels=['grammar'=>'Gramática','vocabulary'=>'Vocabulário','speaking'=>'Fala','listening'=>'Compreensão oral','reading'=>'Leitura','writing'=>'Escrita','fluency'=>'Fluência','pronunciation'=>'Pronúncia'];
$maxEvents=max(1,...array_map(static fn($d)=>(int)$d['sessions']+(int)$d['activities']+(int)$d['messages'],$days));
$trend=null;if(count($history)>=2){$trend=round((float)$history[count($history)-1]['skill_average']-(float)$history[0]['skill_average'],1);}

$pageTitle=(string)$m['name'];
$pageSubtitle='Ficha pedagógica com métricas calculadas diretamente dos registros deste aluno.';
require __DIR__.'/../templates/header.php';
?>

<section class="student-head"><div style="display:flex;align-items:center;gap:17px"><div class="avatar avatar-lg"><?=e(ui_initials((string)$m['name']))?></div><div><div class="list-meta"><span class="badge <?=e(ui_level_class((string)$m['overall_level']))?>"><?=e((string)$m['overall_level'])?></span><span class="badge <?=e(progress_engagement_class((string)$m['engagement_status']))?>"><?=e(progress_engagement_label((string)$m['engagement_status']))?></span><span class="badge <?=e(ui_status_class((string)$m['diagnostic_status']))?>"><?=e(ui_status_label((string)$m['diagnostic_status']))?></span></div><h2><?=e((string)$m['name'])?></h2><div class="label"><?=e((string)($m['phone']?:$m['email']?:'Sem contato'))?> · <?=e((string)$m['goal'])?></div></div></div><div class="hero-stat"><strong><?= (int)$m['xp']?> XP</strong><span><?= (int)$m['streak_days_real']?> dia(s) de sequência · <?=e(ui_relative_date($m['last_activity_at']))?></span></div></section>

<section class="cards cards-4">
    <article class="card metric-card"><div><div class="label">Competências</div><div class="metric"><?=number_format((float)$m['skill_average'],0)?>%</div><div class="metric-sub"><?= (int)$m['skills_measured']?>/8 habilidades medidas<?= $trend!==null?' · '.($trend>=0?'+':'').number_format($trend,1).' pts':''?></div></div><div class="metric-icon"><?=ui_icon('progress')?></div></article>
    <article class="card metric-card"><div><div class="label">Meta semanal</div><div class="metric"><?=number_format((float)$m['week']['goal_percent'],0)?>%</div><div class="metric-sub"><?= (int)$m['week']['completed_minutes']?> min · <?= (int)$m['week']['completed_activities']?> atividades</div></div><div class="metric-icon"><?=ui_icon('target')?></div></article>
    <article class="card metric-card"><div><div class="label">Atividades</div><div class="metric"><?= (int)$m['activities_completed']?>/<?= (int)$m['activities_total']?></div><div class="metric-sub"><?=number_format((float)$m['activity_completion_rate'],0)?>% concluídas · média <?=number_format((float)$m['activity_average_score'],0)?>%</div></div><div class="metric-icon"><?=ui_icon('activities')?></div></article>
    <article class="card metric-card"><div><div class="label">Vocabulário</div><div class="metric"><?= (int)$m['vocabulary_mastered']?></div><div class="metric-sub"><?= (int)$m['vocabulary_total']?> registradas · <?=number_format((float)$m['vocabulary_mastery_rate'],0)?>% dominadas</div></div><div class="metric-icon"><?=ui_icon('vocabulary')?></div></article>
</section>

<div class="grid-2 section-gap">
    <section class="panel"><div class="panel-head"><div><h2>Competências atuais</h2><p>Resultados consolidados do diagnóstico e avaliações da Emma.</p></div></div><?php foreach($skillLabels as $key=>$label):$score=(float)$m['skills'][$key];?><div class="skill"><div class="skill-head"><span><?=e($label)?></span><strong><?= $score>0?number_format($score,0).'%':'Ainda não medida'?></strong></div><div class="progress"><span data-progress="<?=$score?>"></span></div></div><?php endforeach;?></section>
    <section class="panel"><div class="panel-head"><div><h2>Plano e semana</h2><p>Objetivo pedagógico e execução atual.</p></div></div><div class="list-card"><strong><?=e((string)($plan['goal']??'Plano ainda não criado'))?></strong><p><?= $plan?'Meta: '.e((string)$plan['target_level']).' · até '.e(ui_date_only((string)$plan['end_date'])):'Conclua o diagnóstico para gerar o plano.'?></p></div><div class="skill"><div class="skill-head"><span>Minutos registrados</span><strong><?= (int)$m['week']['completed_minutes']?>/<?= (int)$m['week']['target_minutes']?></strong></div><div class="progress"><span data-progress="<?= (float)$m['week']['minutes_pct']?>"></span></div></div><div class="skill"><div class="skill-head"><span>Atividades</span><strong><?= (int)$m['week']['completed_activities']?>/<?= (int)$m['week']['target_activities']?></strong></div><div class="progress"><span data-progress="<?= (float)$m['week']['activities_pct']?>"></span></div></div><div class="skill"><div class="skill-head"><span>Palavras</span><strong><?= (int)$m['week']['learned_words']?>/<?= (int)$m['week']['target_words']?></strong></div><div class="progress"><span data-progress="<?= (float)$m['week']['words_pct']?>"></span></div></div></section>
</div>

<div class="grid-2 section-gap">
    <section class="panel"><div class="panel-head"><div><h2>Atividade em 14 dias</h2><p>Interações reais registradas na plataforma.</p></div></div><div class="weekly-chart admin-activity-chart"><?php foreach($days as $day):$events=(int)$day['sessions']+(int)$day['activities']+(int)$day['messages'];$height=max(7,(int)round(($events/$maxEvents)*100));?><div class="weekly-bar-column"><span class="weekly-value"><?=$events?></span><div class="weekly-bar-track"><span style="height:<?=$height?>%"></span></div><strong><?=e((new DateTimeImmutable((string)$day['day']))->format('d/m'))?></strong></div><?php endforeach;?></div></section>
    <section class="panel"><div class="panel-head"><div><h2>Indicadores de acompanhamento</h2><p>Itens que ajudam a decidir a próxima intervenção.</p></div></div><div class="progress-kpi-list"><div class="list-card"><div class="list-row"><strong>Sessões</strong><span><?= (int)$m['sessions_30d']?> nos últimos 30 dias</span></div></div><div class="list-card"><div class="list-row"><strong>Pendências</strong><span><?= (int)$m['pending_total']?> itens</span></div><p><?= (int)$m['corrections_due']?> correções · <?= (int)$m['vocabulary_due']?> palavras · <?= (int)$m['activities_pending']?> atividades</p></div><div class="list-card"><div class="list-row"><strong>Correções</strong><span><?=number_format((float)$m['corrections_resolved_rate'],0)?>% resolvidas</span></div></div><div class="list-card"><div class="list-row"><strong>Áudio</strong><span><?=number_format((float)$m['voice_minutes_total'],1)?> min registrados</span></div></div></div></section>
</div>

<div class="grid-2 section-gap"><section class="panel"><div class="panel-head"><div><h2>Erros recorrentes</h2><p>Prioridade por recorrência e domínio.</p></div></div><?php if(!$errors):?><div class="empty-state compact"><p>Nenhum erro recorrente em aberto.</p></div><?php else:foreach($errors as $error):?><div class="list-card"><div class="list-row"><strong><?=e((string)($error['topic']?:$error['category']?:'Correção'))?></strong><span class="badge warning"><?= (int)$error['occurrences']?>x</span></div><p><?=e((string)($error['original_text']??''))?><?= $error['corrected_text']?' → '.e((string)$error['corrected_text']):''?></p><div class="progress slim"><span data-progress="<?=progress_clamp($error['mastery_score'])?>"></span></div></div><?php endforeach;endif;?></section><section class="panel"><div class="panel-head"><div><h2>Vocabulário prioritário</h2><p>Palavras mais próximas de revisão.</p></div></div><?php if(!$vocab):?><div class="empty-state compact"><p>Nenhuma palavra registrada.</p></div><?php else:foreach($vocab as $item):?><div class="list-card"><div class="list-row"><strong><?=e((string)$item['word'])?></strong><span class="badge <?=e(ui_status_class((string)$item['status']))?>"><?=e((string)($item['translation']??ui_status_label((string)$item['status'])))?></span></div><p>Domínio <?=number_format((float)$item['mastery_score'],0)?>% · revisão <?=e(ui_date($item['next_review_at']))?></p></div><?php endforeach;endif;?></section></div>

<?php if($diagnostic):?><section class="panel section-gap"><div class="panel-head"><div><h2>Último diagnóstico</h2><p>Resultado salvo em <?=e(ui_date((string)$diagnostic['created_at']))?>.</p></div><span class="badge <?=e(ui_level_class((string)$diagnostic['estimated_level']))?>"><?=e((string)$diagnostic['estimated_level'])?></span></div><div class="grid-3"><div><h3>Pontos fortes</h3><?php foreach(($diagnostic['strengths']??[]) as $item):?><div class="list-card"><p><?=e((string)$item)?></p></div><?php endforeach;?></div><div><h3>Prioridades</h3><?php foreach(($diagnostic['weaknesses']??[]) as $item):?><div class="list-card"><p><?=e((string)$item)?></p></div><?php endforeach;?></div><div><h3>Recomendação</h3><div class="list-card"><p><?=e((string)($diagnostic['written_feedback']??'Sem feedback textual.'))?></p></div></div></div></section><?php endif;?>

<section class="panel section-gap"><div class="panel-head"><div><h2>Sessões recentes</h2><p>Canal, tema e desempenho registrado.</p></div></div><?php if(!$sessions):?><div class="empty-state compact"><p>Nenhuma sessão registrada.</p></div><?php else:?><div class="table-wrap"><table><thead><tr><th>Data</th><th>Canal</th><th>Modo</th><th>Tema</th><th>Status</th><th>Interações</th><th>Gramática</th><th>Fluência</th></tr></thead><tbody><?php foreach($sessions as $session):?><tr><td><?=e(ui_date((string)$session['created_at']))?></td><td><?=e((string)($session['channel']??'—'))?></td><td><?=e(ui_status_label((string)$session['mode']))?></td><td><?=e(ui_topic_label((string)($session['conversation_topic']?:$session['topic'])))?></td><td><span class="badge <?=e(ui_status_class((string)$session['status']))?>"><?=e(ui_status_label((string)$session['status']))?></span></td><td><?= (int)$session['turn_count']?>/<?= (int)$session['max_turns']?></td><td><?=$session['grammar_score']!==null?number_format((float)$session['grammar_score'],0).'%':'—'?></td><td><?=$session['fluency_score']!==null?number_format((float)$session['fluency_score'],0).'%':'—'?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>

<?php if($messages):?><section class="panel section-gap"><div class="panel-head"><div><h2>Últimas mensagens</h2><p>Histórico diretamente vinculado ao cadastro.</p></div></div><div class="timeline"><?php foreach($messages as $message):?><div class="timeline-item"><span class="timeline-dot"></span><strong><?= $message['role']==='teacher'?'Emma':'Aluno'?> · <?=e(ui_status_label((string)$message['message_type']))?></strong><p><?=e(mb_strimwidth((string)($message['content']?:$message['transcription']?:''),0,220,'…'))?></p><time><?=e(ui_date((string)$message['created_at']))?></time></div><?php endforeach;?></div></section><?php endif;?>

<?php require __DIR__.'/../templates/footer.php'; ?>
