<?php
declare(strict_types=1);
require_once __DIR__.'/db.php';
function client_ip(): string { return substr($_SERVER['REMOTE_ADDR'] ?? 'unknown',0,80); }
function csrf_token(): string { if(empty($_SESSION['csrf_token'])) $_SESSION['csrf_token']=bin2hex(random_bytes(32)); return $_SESSION['csrf_token']; }
function csrf_field(): string { return '<input type="hidden" name="csrf_token" value="'.htmlspecialchars(csrf_token(),ENT_QUOTES,'UTF-8').'">'; }
function verify_csrf(): void { $t=(string)($_POST['csrf_token']??''); if($t===''||empty($_SESSION['csrf_token'])||!hash_equals($_SESSION['csrf_token'],$t)){ http_response_code(419); exit('Sessão expirada ou requisição inválida.'); } }
function audit_log(string $action,?string $type=null,?string $id=null,array $meta=[]): void { try{ db()->prepare("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata,ip_address) VALUES(:u,:a,:t,:i,CAST(:m AS jsonb),:ip)")->execute(['u'=>$_SESSION['user_id']??null,'a'=>$action,'t'=>$type,'i'=>$id,'m'=>json_encode($meta,JSON_UNESCAPED_UNICODE),'ip'=>client_ip()]); }catch(Throwable $e){} }
function login_is_rate_limited(string $identifier): bool { try{ $s=db()->prepare("SELECT COUNT(*) FROM login_attempts WHERE success=false AND created_at>=NOW()-INTERVAL '15 minutes' AND (login_identifier=:i OR ip_address=:ip)"); $s->execute(['i'=>$identifier,'ip'=>client_ip()]); return (int)$s->fetchColumn()>=8; }catch(Throwable $e){ return false; } }
function record_login_attempt(string $identifier,bool $success): void { try{ db()->prepare("INSERT INTO login_attempts(login_identifier,ip_address,success) VALUES(:i,:ip,:s)")->execute(['i'=>$identifier,'ip'=>client_ip(),'s'=>$success]); }catch(Throwable $e){} }
function password_is_strong(string $p): bool { return strlen($p)>=8 && preg_match('/[A-Z]/',$p) && preg_match('/[a-z]/',$p) && preg_match('/\\d/',$p); }
function generate_password_reset_token(string $uid,int $minutes=30): string { $plain=bin2hex(random_bytes(32)); $hash=hash('sha256',$plain); db()->prepare("DELETE FROM password_reset_tokens WHERE user_id=:u AND used_at IS NULL")->execute(['u'=>$uid]); db()->prepare("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES(:u,:h,NOW()+(:m||' minutes')::interval)")->execute(['u'=>$uid,'h'=>$hash,'m'=>$minutes]); audit_log('password_reset_token_created','app_user',$uid); return $plain; }
function validate_password_reset_token(string $plain): ?array { if($plain==='')return null; $s=db()->prepare("SELECT p.id token_id,p.user_id,u.name,u.username,u.email,u.phone FROM password_reset_tokens p JOIN app_users u ON u.id=p.user_id WHERE p.token_hash=:h AND p.used_at IS NULL AND p.expires_at>NOW() AND u.status='active' LIMIT 1"); $s->execute(['h'=>hash('sha256',$plain)]); return $s->fetch()?:null; }
